name: build desqueeze for MacOS

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Release title'
        required: true
        default: 'v0.0.0'

jobs:
  build-macos-app:
    runs-on: macos-latest
    timeout-minutes: 10

    strategy:
      matrix:
        os: [mac64]
        include:
        - os: mac64
          goos: darwin
          arch: amd64

    steps:
    - name: Get the version
      id: get_version
      #run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      run: echo ::set-output name=VERSION::${{ github.event.inputs.title }}

    - uses: actions/checkout@v3

    - name: Set up Go 1.17.0
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build go binary
      env:
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.arch }}
      run: |
        mkdir dist
        cp README.md LICENSE dist/
        GOOS=$goos GOARCH=$goarch go build -ldflags="-w -s -X 'main.version=${{ steps.get_version.outputs.VERSION }}' -X 'main.gitcommit=${{ github.sha }}'" -trimpath -v -o dist/desqueeze ./

    - name: Checkout macappshell repo
      uses: actions/checkout@v3
      with:
        repository: Xeoncross/macappshell
        path: build/macappshell

    - name: Checkout create-dmg repo
      uses: actions/checkout@v3
      with:
        repository: create-dmg/create-dmg
        path: build/create-dmg

    # see: https://github.com/Xeoncross/macappshell
    - name: Build DMG
      run: |
        cd build
        ./macappshell/setup.sh desqueeze.app icon/icon.svg
        mv ../dist/desqueeze desqueeze.app/Contents/MacOS/desqueeze
        ./create-dmg/create-dmg \
          --dmg-title='desqueeze-${{ steps.get_version.outputs.VERSION }}'
          desqueeze-${{ steps.get_version.outputs.VERSION }}.dmg \
          desqueeze.app

    - name: TMP - Upload DMG
      uses: actions/upload-artifact@v2
      with:
        name: desqueeze-${{ steps.get_version.outputs.VERSION }}.dmg
        path: build/desqueeze-${{ steps.get_version.outputs.VERSION }}.dmg
        retention-days: 5
