name: Test desqueeze
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13.8
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.8

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Test code
      run: go test -v ./...
